name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build and Deploy
        uses: jekyll/jekyll-action@v0.12.0
        with:
          jekyll_version: 4
          build_options: --trace # Optional: Add additional build options if needed
